services:
  db:
    image: postgres:15-alpine
    container_name: mecanica_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mecanica_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mecanica_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mecanica_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mecanica_db
      SECRET_KEY: dev-secret-key-change-in-production
      FLASK_APP: app
      FLASK_ENV: development
      TEMPLATES_FOLDER: /app/templates
      STATIC_FOLDER: /app/static
      SELENIUM_URL: http://selenium:4444/wd/hub
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend/templates:/app/templates
      - ./frontend/static:/app/static
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mecanica_network
    command: flask run --host=0.0.0.0

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: mecanica_selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    networks:
      - mecanica_network

volumes:
  postgres_data:


networks:
  mecanica_network:
    driver: bridge
